import Header from "@/components/Header";
import Head from "next/head";
import React from "react";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Tiktok</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <h1>Tiktok</h1>
      <div className="w-[90%] mx-auto ">
      <table class="border-collapse border border-slate-400 w-full">
  <thead>
    <tr>
      <th class="border border-slate-300 ...">State</th>
      <th class="border border-slate-300 ...">City</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="border border-slate-300 ...">Indiana</td>
      <td class="border border-slate-300 ...">Indianapolis</td>
    </tr>
    <tr>
      <td class="border border-slate-300 ...">Ohio</td>
      <td class="border border-slate-300 ...">Columbus</td>
    </tr>
    <tr>
      <td class="border border-slate-300 ...">Michigan</td>
      <td class="border border-slate-300 ...">Detroit</td>
    </tr>
  </tbody>
</table>
      </div>
    </div>
  );
}
