import Header from '@/components/Header'
import Head from 'next/head'
import React from 'react'

export default function Index() {
  return (
    
    <div>
        <Head>
            <title>Facebook</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <Header />
        <h1>Facebook</h1>
    </div>
  )
}
