"use client"; // This is a client component 👈🏽
import Header from "@/components/Header";
import Head from 'next/head'
import { useEffect } from "react";


export default function Index() {
    useEffect(() => {
        const fetchData = async () => {
          try {
            const response = await fetch('https://graph.facebook.com/17841405822304914/insights?metric=impressions,reach,profile_views&period=day');
            if (!response.ok) {
              throw new Error('Network response was not ok');
            }
            const result = await response.json();
            console.log(result);
          } catch (error) {
            console.error('Error fetching data:', error);
          }
        };
      
        fetchData();
      }, []);
      
    return (
        <div>
            <Head>
                <title>Instagram</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header />
            <h1>Instagram</h1>
        </div>
    )
}